name: genome_diversity

dependencies:
  # perl is almost always installed with core linux installations
  # step 02 & 03
  - bbmap=38.90 #bionconda # this should include bbtools (bbduk, bbnorm)
  # step 04
  ## uses perl
  ## uses enveomics
  ## Need python for the subsampling script.
  - python=3.7.1 #anaconda - I think this is the default channel
  - idba=1.1.3 #bioconda
  # step 05
  - maxbin2=2.2.7 #bionconda
  # step 06
  - metabat2=2.15 #bionconda
  # future step 07
  - vamb=3.0.2 #bionconda
  # current step 07
  ## uses miga
  # current step 08
  ## uses enveomics
  ## uses perl
  - samtools=1.12 #bionconda
  - parallel=20210422 #conda-forge
  - ruby=2.7.2 #conda-forge
  - bcftools=1.12 #bionconda

channels:
  - conda-forge
  - bioconda

#########################################################################
#########################################################################

  # Not required:
  # Used by MiGA but not the genome diversity workflow

  # General-purpose
  #- r-base=3.6 #conda-forge  
  #- sqlite=3.35.4 #anaconda
  #- openjdk=11.09.1 #conda-forge

  # Read processing
  #- faqcs=2.10 #bioconda
  #- falco=0.2.4 #bioconda
  #- seqtk=1.3 #bioconda
  #- fastp=0.20.1 #bioconda
  
  # Assembly processing
  #- hmmer=3.3.2 #bioconda # covered by maxbin2 depends
  #- bedtools=2.30.0 #bioconda
  #- prodigal=2.6.3 #bioconda
  #- barrnap=0.9 #bioconda
  #- krona=2.7.1 #bioconda

  # Distances
  #- blast=2.11.0 #bioconda
  #- mcl=14.137 #bioconda
  #- diamond=2.0.9 #bionconda
  #- fastani=1.32 #bionconda



